export const EXERCISE_LIBRARY = [
  { name: "벤치프레스", muscleGroup: "가슴", icon: "press" },
  { name: "인클라인 벤치프레스", muscleGroup: "가슴", icon: "press" },
  { name: "덤벨 벤치프레스", muscleGroup: "가슴", icon: "press" },
  { name: "덤벨 플라이", muscleGroup: "가슴", icon: "raise" },
  { name: "푸시업", muscleGroup: "가슴", icon: "press" },
  { name: "딥스", muscleGroup: "가슴", icon: "press" },
  { name: "케이블 크로스오버", muscleGroup: "가슴", icon: "machine" },
  { name: "펙 덱 플라이", muscleGroup: "가슴", icon: "machine" },

  { name: "데드리프트", muscleGroup: "등", icon: "hinge" },
  { name: "바벨 로우", muscleGroup: "등", icon: "pull" },
  { name: "덤벨 로우", muscleGroup: "등", icon: "pull" },
  { name: "풀업", muscleGroup: "등", icon: "pull" },
  { name: "랫풀다운", muscleGroup: "등", icon: "machine" },
  { name: "시티드 로우", muscleGroup: "등", icon: "machine" },

  { name: "오버헤드 프레스", muscleGroup: "어깨", icon: "press" },
  { name: "덤벨 숄더프레스", muscleGroup: "어깨", icon: "press" },
  { name: "사이드 레터럴 레이즈", muscleGroup: "어깨", icon: "raise" },
  { name: "프론트 레이즈", muscleGroup: "어깨", icon: "raise" },
  { name: "리어 델트 플라이", muscleGroup: "어깨", icon: "raise" },
  { name: "페이스 풀", muscleGroup: "어깨", icon: "pull" },

  { name: "바벨 컬", muscleGroup: "팔", icon: "curl" },
  { name: "덤벨 컬", muscleGroup: "팔", icon: "curl" },
  { name: "해머 컬", muscleGroup: "팔", icon: "curl" },
  { name: "트라이셉스 익스텐션", muscleGroup: "팔", icon: "curl" },
  { name: "케이블 푸시다운", muscleGroup: "팔", icon: "machine" },
  { name: "삼두 딥스", muscleGroup: "팔", icon: "press" },

  { name: "스쿼트", muscleGroup: "하체", icon: "squat" },
  { name: "런지", muscleGroup: "하체", icon: "squat" },
  { name: "레그프레스", muscleGroup: "하체", icon: "machine" },
  { name: "레그컬", muscleGroup: "하체", icon: "machine" },
  { name: "레그익스텐션", muscleGroup: "하체", icon: "machine" },
  { name: "루마니안 데드리프트", muscleGroup: "하체", icon: "hinge" },
  { name: "힙 쓰러스트", muscleGroup: "하체", icon: "hinge" },
  { name: "카프레이즈", muscleGroup: "하체", icon: "raise" },

  { name: "플랭크", muscleGroup: "코어", icon: "core" },
  { name: "크런치", muscleGroup: "코어", icon: "core" },
  { name: "레그레이즈", muscleGroup: "코어", icon: "core" },
  { name: "행잉 레그레이즈", muscleGroup: "코어", icon: "core" },
  { name: "러시안 트위스트", muscleGroup: "코어", icon: "core" },

  { name: "러닝", muscleGroup: "유산소", icon: "cardio" },
  { name: "사이클", muscleGroup: "유산소", icon: "cardio" },
  { name: "로잉머신", muscleGroup: "유산소", icon: "cardio" },
  { name: "걷기", muscleGroup: "유산소", icon: "cardio" },
];
